fieldLayouts:
  5e88901a-146e-4a93-b10d-072f674d1c8c:
    tabs:
      -
        elementCondition: null
        elements:
          -
            autocapitalize: true
            autocomplete: false
            autocorrect: true
            class: null
            disabled: false
            elementCondition: null
            id: null
            instructions: null
            label: null
            max: null
            min: null
            name: null
            orientation: null
            placeholder: null
            readonly: false
            requirable: false
            size: null
            step: null
            tip: null
            title: null
            type: craft\fieldlayoutelements\entries\EntryTitleField
            uid: 9648db3e-7cd4-4ad4-9b6c-ae98447e49fb
            userCondition: null
            warning: null
            width: 100
          -
            elementCondition: null
            fieldUid: c7dc945f-f527-4e61-b5ba-1dd07244f416 # Description
            instructions: null
            label: null
            required: false
            tip: null
            type: craft\fieldlayoutelements\CustomField
            uid: c6537035-e76f-44d8-a76f-92e460e5c5c8
            userCondition: null
            warning: null
            width: 100
          -
            elementCondition: null
            fieldUid: 1d47e28c-030d-4a1e-84fe-aca0cbf26112 # NFT Image
            instructions: null
            label: null
            required: false
            tip: null
            type: craft\fieldlayoutelements\CustomField
            uid: 41d36ca1-1576-4edd-9486-67a87b5fdf84
            userCondition: null
            warning: null
            width: 100
          -
            elementCondition: null
            type: craft\fieldlayoutelements\LineBreak
            uid: fbaab89f-7cb8-428a-a12e-07a17f2328e0
            userCondition: null
          -
            elementCondition: null
            fieldUid: 44ff9df3-b421-4819-bb38-b54cd25c65c4 # Sales Price
            instructions: null
            label: null
            required: false
            tip: null
            type: craft\fieldlayoutelements\CustomField
            uid: 16dad12d-c9ae-443a-8c51-308e0dce131d
            userCondition: null
            warning: null
            width: 25
          -
            elementCondition: null
            fieldUid: 6071fff8-2b8f-481e-94c7-f89bff139e8f # Sales End Date
            instructions: null
            label: null
            required: false
            tip: null
            type: craft\fieldlayoutelements\CustomField
            uid: 73b1c70c-3ef5-408c-9bb9-27e0871c1abf
            userCondition: null
            warning: null
            width: 25
          -
            elementCondition: null
            fieldUid: 5eafcf51-f9db-4583-9a19-1fdb309694f7 # Sales Start Date
            instructions: null
            label: null
            required: false
            tip: null
            type: craft\fieldlayoutelements\CustomField
            uid: 2a611f3b-980f-4c4b-b852-2c4b6d253287
            userCondition: null
            warning: null
            width: 25
        name: Content
        uid: 1068149c-6048-48b4-a106-48975079ce7e
        userCondition: null
handle: default
hasTitleField: true
name: Default
section: 954fbdf1-5b70-46d8-92e3-2017d987725d # NFT
sortOrder: 1
titleFormat: null
titleTranslationKeyFormat: null
titleTranslationMethod: site
