columnSuffix: null
contentColumnType: string
fieldGroup: 540bed18-5b7e-4ffe-9728-fc9e00196596 # NFT
handle: nftImage
instructions: null
name: 'NFT Image'
searchable: false
settings:
  allowSelfRelations: false
  allowSubfolders: false
  allowUploads: true
  allowedKinds: null
  defaultUploadLocationSource: 'volume:de202251-41b3-44d2-85e7-75ada9a43c30' # NFT Image
  defaultUploadLocationSubpath: null
  localizeRelations: false
  maxRelations: null
  minRelations: null
  previewMode: full
  restrictFiles: false
  restrictLocation: false
  restrictedDefaultUploadSubpath: null
  restrictedLocationSource: 'volume:de202251-41b3-44d2-85e7-75ada9a43c30' # NFT Image
  restrictedLocationSubpath: null
  selectionCondition:
    __assoc__:
      -
        - elementType
        - craft\elements\Asset
      -
        - fieldContext
        - global
      -
        - class
        - craft\elements\conditions\assets\AssetCondition
  selectionLabel: null
  showSiteMenu: false
  showUnpermittedFiles: false
  showUnpermittedVolumes: false
  source: null
  sources:
    - 'volume:de202251-41b3-44d2-85e7-75ada9a43c30' # NFT Image
  targetSiteId: null
  validateRelatedElements: false
  viewMode: list
translationKeyFormat: null
translationMethod: site
type: craft\fields\Assets
