columnSuffix: fkbnssds
contentColumnType: 'decimal(12,2)'
fieldGroup: 540bed18-5b7e-4ffe-9728-fc9e00196596 # NFT
handle: salesPrice
instructions: null
name: 'Sales Price'
searchable: false
settings:
  decimals: 2
  defaultValue: null
  max: null
  min: 0
  prefix: null
  previewCurrency: null
  previewFormat: decimal
  size: null
  suffix: null
translationKeyFormat: null
translationMethod: none
type: craft\fields\Number
