columnSuffix: yaaboafm
contentColumnType: datetime
fieldGroup: 540bed18-5b7e-4ffe-9728-fc9e00196596 # NFT
handle: salesEndDate
instructions: null
name: 'Sales End Date'
searchable: false
settings:
  max: null
  min: null
  minuteIncrement: 30
  showDate: true
  showTime: true
  showTimeZone: false
translationKeyFormat: null
translationMethod: none
type: craft\fields\Date
